# Application dependent names and paths
from KratosMultiphysics import _ImportApplication, python_registry_utilities
from KratosGroundFreezingApplication import *

application = KratosGroundFreezingApplication()
application_name = "KratosGroundFreezingApplication"

_ImportApplication(application, application_name)

from . import python_registry_lists
python_registry_utilities.RegisterModelersList("KratosMultiphysics.GroundFreezingApplication", python_registry_lists)
python_registry_utilities.RegisterOperationsList("KratosMultiphysics.GroundFreezingApplication", python_registry_lists)
python_registry_utilities.RegisterProcessesList("KratosMultiphysics.GroundFreezingApplication", python_registry_lists)